import os

YOUTUBE_API_KEY_1 = os.getenv('YOUTUBE_API_KEY_1', 'YOUR_YOUTUBE_API_KEY')
YOUTUBE_API_KEY_2 = os.getenv('YOUTUBE_API_KEY_2', 'YOUR_YOUTUBE_API_KEY')
YOUTUBE_API_KEY_3 = os.getenv('YOUTUBE_API_KEY_3', 'YOUR_YOUTUBE_API_KEY')
# YOUTUBE_API_KEY_4 = os.getenv('YOUTUBE_API_KEY_4', 'YOUR_YOUTUBE_API_KEY')
RABBITMQ_URL = os.getenv('RABBITMQ_URL', 'amqp://guest:guest@localhost:5672/')
QUEUE_NAME = 'youtube_comments'
EXCEL_OUTPUT_DIR = 'output/'
CHANNEL_ID = os.getenv('CHANNEL_ID', 'CHANNEL_ID')
EXCLUDE_VIDEOS=['_mljnxa9IR4','vDViqlhEjyI']
PUBLISHED_AFTER='2016-01-01T00:00:00Z'
PUBLISHED_BEFORE='2016-12-01T23:59:59Z'
COMMENT_PUBLISHED_BEFORE='2017-12-01T23:59:59Z'
